language: cpp
os:
  osx

jobs:
  include:
    - os: osx
      osx_image: xcode11
      dist: trusty
      env:
        - LDFLAGS="-L/usr/local/opt/llvm/lib"
        - CPPFLAGS="-I/usr/local/opt/llvm/include"
      addons:
        homebrew:
          packages:
            - clang
            - ninja
            - cmake
            - openssl

script:
  - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -H. -B./build -G "Ninja"
  - cmake --build ./build
