language: cpp

jobs:
  include:
    -os: osx
    os_image: xcode11
    dist: trusty


before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update  ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install openssl; fi

script:
  - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -H. -B./build
  - cmake --build ./build
