language: cpp
os:
  osx

jobs:
  include:
    - os: osx
      osx_image: xcode11
      dist: trusty
      cache:
        ccache: true
        directories:
          - $HOME/Library/Caches/Homebrew
      env:
        - LDFLAGS="-L$(brew --prefix llvm)/lib"
        - CPPFLAGS="-I$(brew --prefix llvm)/include"
      addons:
        homebrew:
          packages:
            - llvm
            - ninja
            - cmake
            - openssl

script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export CXX=$(brew --prefix llvm)/bin/clang++; fi
  - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -H. -B./build -G "Ninja"
  - cmake --build ./build
